language: python

python:
  - "2.7"

install:
  - sudo apt-get install sqlite3 libpq-dev
  - sudo apt-get install python-pip python-dev
  - pip install -r requirements.txt --use-mirrors

script:
  - py.test tests

